import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers/Providers";
import Sidebar from "./components/Sidebar/Sidebar";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hardware Picker AI 🇸🇪 - your personal PC builder assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <Providers>
          <div className="min-h-screen bg-background text-foreground">
            <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
              <div className="absolute inset-0 bg-gradient-hero" />
              <div className="absolute top-20 left-1/4 w-96 h-96 bg-gradient-glow animate-glow" />
              <div
                className="absolute bottom-20 right-1/4 w-96 h-96 bg-gradient-glow animate-glow"
                style={{ animationDelay: "1s" }}
              />

              <div className="container mx-auto px-6 lg:px-12 relative z-10">
                <div className="grid lg:grid-cols-2 gap-12 items-center">
                  <main className="flex-1 lg:w-1/2">{children}</main>
                  <Sidebar />
                </div>
              </div>
            </section>
          </div>
        </Providers>
      </body>
    </html>
  );
}
